# Generated by Django 4.2.4 on 2023-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='manager',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
