# Generated by Django 4.2.5 on 2024-02-27 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_group_ordersmodel_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='course',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(FS|QACX|JCX|JSCX|FE|PCX)?$', 'you can specify the course: FS, QACX, JCX, JSCX, FE, PCX or do not specify anything')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='course_format',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(static|online)?$', 'you can specify the course_type: static, online or do not specify anything')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='course_type',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^(pro|minimal|premium|incubator|vip)?$', 'you can specify the course_type: pro, minimal, premium, incubator, vip or do not specify anything')]),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(In work|New|Agree|Disagree|Dubbing)?$', 'you can specify the status: In work, New, Agree, Disagree, Dubbing or do not specify anything')]),
        ),
    ]
