# Generated by Django 4.2.5 on 2024-02-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('orders', '0003_alter_ordersmodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='groups.groupsmodel'),
        ),
    ]
