# Generated by Django 5.0.3 on 2024-04-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordersmodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='user',
        ),
    ]
