# Generated by Django 4.2.5 on 2024-02-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsmodel',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
